name: Go version compatibility

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.24", "stable"]
        os: [ubuntu-latest, ubuntu-24.04-arm]
    name: Go ${{ matrix.go }} build
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: '1'

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go }}

      - name: Download dependencies
        run: go mod tidy

      - name: Build landrun
        run: go build ./cmd/landrun
